# --------------- 输入文件 ---------------
# 物种丰度表
taxon_df <- './03_exported_tables/order_table.tsv'

# 分组表
map_df <- './03_exported_tables/map.tsv'

# --------------- 输出文件 ---------------
# 输出路径
output <- './04_figures/01_barplot'

# 输出文件
output.file <- 'barplot'

# --------------- 绘图参数 ---------------
# 截取丰度前 topN 值
topN <- 10

# 颜色
colors.list <- c("#88cbc0", "#f6f5b3", "#bbb7d6", "#ee7d6f", "#7fabca", 
    "#f4af64", "#add26b", "#f6cade", "#b37cb4", "#c8e3c0", "#999999")

# 图像宽度
width <- 8

# 图像高度
height <- 3

# x轴标题字体大小
x.title.size <- 7

# x轴标签字体大小
x.size <- 5

# x轴标签旋转角度
x.angle <- 90

# x轴标签水平对齐方式
x.hjust <- 1

# y轴标题字体大小
y.title.size <- 7

# y轴标签字体大小
y.size <- 5

# y轴标签旋转角度
y.angle <- 0    

# y轴标签水平对齐方式
y.hjust <- 0

# 图例标题字体大小
legend.title.size <- 7

# 图例标签字体大小
legend.text.size <- 5

# 图例色块大小
legend.key.size <- 0.15




