# --------------- 输入文件 ---------------
# 物种丰度表
taxon_df <- "./03_exported_tables/rarefied_asv_table.tsv"

# 分组表
map_df <- "./03_exported_tables/map.tsv"

# --------------- 输出文件 ---------------
# 输出路径
output <- "04_figures/02_alpha_diversity"

# 输出文件
output.file <- "alpha_diversity"

# --------------- 绘图控制 ---------------
# 是否按组进行绘图
# 可选值: TRUE, FALSE
plot_by_group <- TRUE

# --------------- 绘图参数 ---------------

# 多样性指数
# 可选值: "Richness", "Shannon", "Simpson"，"Chao1"，"ACE"
index <- "Richness"

# 箱线图填充颜色
color.list <- c("#FDEBAA", "#EDC3A5", "#DBE4FB", "#ABD1BC", "#E3BBED", "#CCCC99", 
                "#BED0F9", "#FCB6A5", "#F1F1F1")

# 图像宽度
width <- 8

# 图像高度
height <- 5

# x轴标题字体大小
x.title.size <- 7

# x轴标签字体大小
x.size <- 5

# x轴标签旋转角度
x.angle <- 90

# x轴标签水平对齐方式
x.hjust <- 1

# y轴标题字体大小
y.title.size <- 7

# y轴标签字体大小
y.size <- 5

# y轴标签旋转角度
y.angle <- 0    

# y轴标签水平对齐方式
y.hjust <- 0