# --------------- 输入文件 ---------------
# 物种丰度表
taxon_df <- "./03_exported_tables/rarefied_asv_table.tsv"

# 分组表
map_df <- "./03_exported_tables/map.tsv"

# 环境因子表
metadata_df <- "./03_exported_tables/metadata.tsv"
factors <- c("Treat", "Time")

# --------------- 输出文件 ---------------
# 输出路径
output <- "04_figures/03_beta_diversity"

# 输出文件
output.file <- "PCoA"

# --------------- 绘图控制 ---------------
# 是否按组进行绘图
# 可选值: 
method <- "bray"

# --------------- 绘图参数 ---------------

# 填充颜色
color.list <- c("#FDEBAA", "#EDC3A5", "#DBE4FB", "#ABD1BC", "#E3BBED", "#CCCC99", 
                "#BED0F9", "#FCB6A5", "#F1F1F1")

# 图像宽度
width <- 4.5

# 图像高度
height <- 4

# x轴标题字体大小
x.title.size <- 9

# x轴标签字体大小
x.size <- 7

# x轴标签旋转角度
x.angle <- 90

# x轴标签水平对齐方式
x.hjust <- 1

# y轴标题字体大小
y.title.size <- 9

# y轴标签字体大小
y.size <- 7

# y轴标签旋转角度
y.angle <- 0    

# y轴标签水平对齐方式
y.hjust <- 0