# --------------- 输入文件 --------------- #
# 物种丰度表
otu_df <- "./03_exported_tables/rarefied_asv_table.tsv"

# 分组表
metadata_df <- "./03_exported_tables/metadata.tsv"

# 环境因子表
tax_df <- "./03_exported_tables/seq2asvid.tsv"

# --------------- 输出文件 --------------- #
# 输出路径
output <- "04_figures/04_lefse"

# 输出表格：LDA显著性分析结果
lefse_table <- "lefse_result"

# 输出图片：LDA显著性分析 bar
lefse_bar <- "lefse_bar"

# 输出图片：LDA显著性分析 cladogram
lefse_cladogram <- "lefse_cladogram"

# --------------- 参数控制 --------------- #
# 分组变量
group <- "Tissue"

# LDA阈值
lda_threshold <- 2

# 显示的特征数量
feature_num <- 20

# 显示的分类单元数量
use_taxa_num <- 200

# 显示的分类单元层级
clade_label_level <- 6

# --------------- 绘图控制 --------------- #
# LDA显著性分析 bar
# 图像宽度
bar.width <- 8

# 图像高度
bar.height <- 8

# LDA显著性分析 cladogram
# 图像宽度
cladogram.width <- 8

# 图像高度
cladogram.height <- 6
