# --------------- 输入文件 ---------------
# 物种丰度表
otu_df <- "./03_exported_tables/order_table.tsv" 

# 环境因子表
env_df <- "./00_user_tables/chem_params.tsv"

env_variables <- c("Salinity", "pH", "Fe_iw", "Mn_iw", "P_iw", "depth", "TOC")

flag <- "SED"

# 分组表
map_df <- paste0('./00_user_tables/map_', flag, '.tsv')

# --------------- 输出文件 ---------------
# 输出路径
output <- './04_figures/05_dbRDA'

output_file <- paste0("dbRDA_", flag,"_plot.pdf")