# --------------- 输入文件 ---------------
# 物种丰度表
otu_df <- "./03_exported_tables/order_table.tsv" 

# 环境因子表
env_df <- "./00_user_tables/chem_params.tsv"

env_variables <- c("Salinity", "SO4_iw", "TOC", "Ca_iw", "Fe_iw")



# 分组表
map_df <- './00_user_tables/map_SED.tsv'

# --------------- 输出文件 ---------------
# 输出路径
output <- './04_figures/06_mantel'