# --------------- 输入文件 ---------------
# 物种丰度表
taxon_df <- './03_exported_tables/rarefied_asv_table.tsv'

# 分组表
map_df <- './03_exported_tables/metadata.tsv'

# 进化树
tree_file <- './03_exported_tables/tree.nwk'

# --------------- 输出文件 ---------------
# 输出路径
output <- './04_figures/05_icamp'

# 输出文件
output.file <- 'icamp'

# --------------- 选择分组 ---------------
group <- 'Tissue'